#!/bin/sh
builddir="build"
name=${PWD##*/}
contents="cmake_minimum_required(VERSION 3.10)
project($name)
file(GLOB_RECURSE SOURCES RELATIVE \${CMAKE_SOURCE_DIR} \"./src/*.cpp\")
add_executable($name \${SOURCES})
set_property(TARGET $name PROPERTY CXX_STANDARD 20)
include_directories(include)

#Optional:
#target_link_libraries($name LLVM)
"
main="#include <iostream>

int main() {

}"
mkdir src
mkdir include
echo "$main" > "src/main.cpp"
echo "$contents" > CMakeLists.txt
cmake -H. -B"$builddir" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
ln -s "$builddir"/compile_commands.json .
