#!/bin/bash
choice=$(echo -e "shutdown\nreboot\nlogout" | rofi -dmenu -i -p system)
[ -z "$choice" ] && exit 0
echo "$choice"

case $choice in
	shutdown) shutdown -P now;;
	reboot) shutdown -r now;;
	logout) i3-msg exit;;
esac
