#!/bin/bash
curl -s wttr.in > ~/.cache/weather
cp ~/.cache/weather ~/.cache/weather-parseable
#cp ~/.cache/weather ~/.cache/weather-stripped
sed -i 's,\x1B\[[0-9;]*[a-zA-Z],\ ,g' ~/.cache/weather-parseable
#sed -i 's,\x1B\[[0-9;]*[a-zA-Z],,g' ~/.cache/weather-stripped
#awk 'NR == 4 {printf("%d%s ←→ %d%s", $4, $7, $6, $7)}' ~/.cache/weather-parseable
curl -s wttr.in/?format=2 | sed 's/[^[:alnum:]_-_+_°_/]/ /g' | awk '{printf("%s, %s%s", $1, $2, $3)}' #> ~/.cache/weather-stripped
